### ISSUE TITLE
wave error

### ISSUE THREAD

**Issue by jrpool** [cvs-health/testaro#15]
A commentator says that the `wave` tool mismeasures background color on aaatraq.com and hypothesizes that wave fails to handle CSS variables. Verify. If confirmed, report as an issue to WebAIM.

**Comment by poolcvs** [comment]
Retested. The test for `wave` rule `contrast` was found to demand a background color that contrasts with the text color, regardless of whether the background also has a background image, because of the fact that images, including background images, are not always displayed. On retest, it was found that suppressing images with Chrome security and privacy settings made some texts invisible or nearly invisible, because the text color was white and the background color was unset and defaulted to white. This rule is well-founded and the test behavior is appropriate.
