### ISSUE TITLE
Autocomplete values

### ISSUE THREAD

**Issue by jrpool** [cvs-health/testaro#25]
Investigate whether packages test for appropriate autocomplete values and, if not, whether it is feasible to test for them. If so, add a test.

**Comment by poolcvs** [comment]
An `autocomplete` rule was added to `testaro` to require the `given-name`, `family-name`, and `email` `autocomplete` attributes where applicable. It is configurable and has defaults for English. It is assigned a quality of 0.5 in `tic37` in `testilo` because of the risk of misclassification. This is a good candidate for a custom rule for a specific design system.
