### ISSUE TITLE
E404 While installing testaro though npm

### ISSUE THREAD

**Issue by ecomback-official** [cvs-health/testaro#31]
Hi jonathan,

To begin, I just wanted to say thanks for such an amazing tool. My team and I have been working on a WordPress project and have been trying to incorporate your accessibility tool. We have carried out the documents in accordance with the instructions that you given.  However, there is a problem that we are experiencing, and regarding that error, we have not been able to locate any aid. Could you kindly assist us with resolving this matter?

We are using MAC terminal, and the command that we are running is
npm i testaro.
and this command work fine at start but after some time it gives following issue.
Issue: Error 404
GET request to the URL https://registry.npmjs.org/@siteimprove%2falfa-act resulted in a 404 error.

We have generated the token using the git account, and the file .npmrc containing it is located in the root folder of the wordpress project. We are grateful for any assistance that you may provide.

**Comment by jrpool** [comment]
Thank you, @ecomback-offical, for making use of this package.

I believe that the problem arises from the fact that the alfa packages belonging to the siteimprove scope are not on npmjs. They are Github packages.

The README file has an Installation section that explains this and specifies what your .npmrc file must contain in order to make the installer obtain the alfa packages from Github instead of npmjs.

Please let me know if this does not solve the problem.

**Comment by poolcvs** [comment]
Issue presumed resolved.
