### ISSUE TITLE
Check possible invalid reports by ASLint and WAVE that https://equalify.app/ has no h1 element

### ISSUE THREAD

**Issue by poolcvs** [cvs-health/testaro#35]
These reports were delivered on 2023-11-30.

**Comment by jrpool** [comment]
The DOM was inspected and found to contain an `h1` element. The same tests were repeated. On the repetition, neither tool reported an `h1`-missing violation. No method is known for diagnosing the previous violation reports. Since the error cannot be reproduced, it is appropriate to resolve the issue and not to deprecate either rule.
