### ISSUE TITLE
Investigate editoria11y as an additional tool

### ISSUE THREAD

**Issue by poolcvs** [cvs-health/testaro#37]
Investigate whether the editoria11y tool (https://editoria11y.princeton.edu) can be and merits being added to Testaro. Suggested by @bbertucc.

**Comment by bbertucc** [comment]
Tagging @itmaybejj, editoria11y's creator. 

Might also be worth checking out [sa11y](https://github.com/ryersondmp/sa11y) which editoria11y was forked from.

**Comment by itmaybejj** [comment]
Both Sa11y and Editoria11y have headless modes. 

By the end of the week I will have rewritten my Results object to use roughly the same syntax as Sa11y. So once that is done you could absolutely call either library and then [wait for a JS event](https://git.drupalcode.org/project/editoria11y/-/blob/2.1.x/js/editoria11y-drupal.js?ref_type=heads#L191) saying results were ready, and then "harvest" the results object into whatever format you wanted.

The result object looks like 
```
{
        element
        test (test name as key, can be used to pull the nice name of the test from the localization files)
        content (text for the tooltip)
        position (not of interest to you)
        dismissalKey (not of interest to you)
        dismissalStatus (not of interest to you)
}
```

**Comment by poolcvs** [comment]
> you could absolutely call either library and then [wait for a JS event](https://git.drupalcode.org/project/editoria11y/-/blob/2.1.x/js/editoria11y-drupal.js?ref_type=heads#L191) saying results were ready, and then "harvest" the results object into whatever format you wanted.

Thank you, @itmaybejj, for the encouragement. I think I need a bit more help. What is meant by “call … library” in this context?

**Comment by itmaybejj** [comment]
Something like this:

`<script src="/PATH/TO/YOUR/COPY/editoria11y.min.js"></script>`
```
  <script>
    document.addEventListener('ed11yResults', function () {
      // yourFunctionToReadResults();
    });

    const ed11y = new Ed11y({
      alertMode = 'headless',
    });
  </script>
```
Headless is optional but will take less CPU -- it just stops before drawing the UI. Other params and code samples for adding custom tests in the [config notes](https://editoria11y.princeton.edu/configuration/).

You'd then need a function to read the Ed11y.results() object and report back in your preferred format.
The Drupal module [parses the array to create a count of each issue type](https://git.drupalcode.org/project/editoria11y/-/blob/2.1.x/js/editoria11y-drupal.js?ref_type=heads#L142) and then [exports that as JSON](https://git.drupalcode.org/project/editoria11y/-/blob/2.1.x/js/editoria11y-drupal.js?ref_type=heads#L167).

I just tagged v2.1.0 with the new object syntax, so that will help.

Sa11y also tagged a new release this week, with a built-in [exporter to CSV or HTML](https://github.com/ryersondmp/sa11y/blob/master/src/js/features/export-results.js). Might be some very useful tidbits in there.

**Comment by poolcvs** [comment]
Thank you for the help, @itmaybejj.

On the basis of a small sample, I am examining the `result` array for identification of the elements. I see only an empty object as the value of the `element` property of each result. The `dismissalKey` property in some cases is a collapsed version of the text content. The `position` property always has the value `beforebegin`. The `content` property in some cases identifies (somewhere within the unstructured text) a distinctive fact about the element, such as its link text.

The other tools integrated by Testaro give one or more of the page location (as CSS selector, XPath, line number, or coordinates), `id` value (if any), tag name, and code excerpt. Any of these helps identify the element exhibiting the issue. Am I missing any element-identifying information that is in the 'result` array or can be obtained?

**Comment by itmaybejj** [comment]
Within the result array on the page, the element property is a direct reference to the node itself. So that's probably why it's showing up as an empty object after export.

What I would do is grab whatever you want out of that node reference before exporting, while your tool is still examining the page.

E.g., grab an [XPath generator](https://stackoverflow.com/questions/2661818/javascript-get-xpath-of-a-node), and do something like (writing this on the fly so no promises it runs unmodified...)
```
// ---
// pasting code here from that StackOverflow or equivalent with createXPathFromElement() to get ID or xPath
// ---

document.addEventListener('ed11yResults', function () {

  let exportArray = []

  Ed11y.results?.forEach(result => {
    exportArray.push({
      xPath: createXPathFromElement(result.element),
      tagName: result.element.tagName,
      codeExcerpt: result.element.outerHTML,
      resultMachineName: result.test,
      resultNiceName: Ed11y.M[result.test].title,
      resultHelpText: result.content,
      severity: result.dismissalKey ? 'Manual check' : 'Error',
    })
  })

  // Your code to export the exportArray to your tool.

});
```

If there is a growing consensus for desired keys and content for what makes a good export array, I could conceivably pull that code into the library or a sidecar repo.

**Comment by poolcvs** [comment]
@itmaybejj: That solves the problem! Thanks much.

**Comment by poolcvs** [comment]
Editoria11y has now been integrated into Testaro, version 33.0.0, as one of 10 testing tools. Thanks to @itmaybejj for helping make this possible.

**Comment by bbertucc** [comment]
Can't wait to try it!

**Comment by poolcvs** [comment]
The version of Testaro that is available for the demo web application has not yet been updated. Updating awaits incorporation of the Editoria11y rules into the issue classification of Testilo, to enable reporting of Editoria11y results.

**Comment by bbertucc** [comment]
> The version of Testaro that is available for the demo web application 

Thanks! I'm following and will watch for updates.
